tags support
manuelernestog/astrofy pull request #38
Opened 2023-09-09 01:26 UTC by brahimABD98

added tags support  but for one  tag at the time  it will crawl all the posts and look for all the tags and generate the paths accordingly with pagination 

- zod repo has a pr that will add array uniqueness checks [see](https://github.com/colinhacks/zod/pull/2672/commits)
- HorizontalCard is only used by the blog for now so idk if tag_url is even required
- added aliases for both components and layouts

2023-10-05 12:17 UTC, hmenorjr commented
@brahimABD98 Hi, do you have a screenshot of this?

2023-10-05 14:24 UTC, brahimABD98 commented
@hmenorjr Oh this means you can filter posts using one tag  at a time (you can't filter using multiple tags at once ) but you can add multiple tags to each post  and they have to be unique 
screenshot :

<img src="https://github.com/manuelernestog/astrofy/assets/47871510/a9303bce-8204-4dd9-b78e-ead29a6b6d1c" width=400>

2023-10-05 15:27 UTC, manuelernestog requested changes
Excellent work @brahimABD98 !

I leave you some small change requests. 

Also, you need to pull the code in the PR branch because I had to merge the master branch to fix some conflicts with new changes.

2023-10-05 15:27 UTC, manuelernestog commented on src/pages/blog/tag/[tag]/[...page].astro
> +                        <HorizontalCard
As we are going to add support for tags, we should include the tags in all blog post cards. Let's add the `tags={post.data.tags}` here

2023-10-05 15:27 UTC, manuelernestog commented on src/pages/blog/tag/[tag]/[...page].astro
> +<BaseLayout title="Blog" sideBarActiveItemID="blog">
Here we can add a dynamic Title according to the tag selected. Something like `Blog - [tagname]`

2023-10-05 15:27 UTC, manuelernestog commented on src/pages/blog/tag/[tag]/[...page].astro
> +        <div class="text-3xl w-full font-bold">Blog</div>
Let's add the tag name here too

2023-10-05 16:42 UTC, brahimABD98 commented
@manuelernestog all good to go

2023-10-05 19:28 UTC, manuelernestog approved these changes

2023-10-05 19:29 UTC, merged

2023-10-06 06:33 UTC, hmenorjr commented
@brahimABD98 Awesome, thanks. I was thinking of how to add a tag in the `HorizontalCard` since it's in a some sort of for-loop. I just got back to development for my website. So yeah, thanks. Like this template for SEO and simplicity. thanks again.